"""
keyword_build.py — Generate config/keywords.py from the org chart.

Pulls canonical dept/section names from config/org.py and expands each into
a set of natural-language keywords algorithmically (suffix stripping, known
abbreviations, compound splits). Writes the result to config/keywords.py.

Run this script whenever the org structure changes, or to add new keywords:
    python config/keyword_build.py

For LLM-assisted expansion (future):
    python config/keyword_build.py --llm
"""
import argparse
import sys
from pathlib import Path

# Allow running from project root
sys.path.insert(0, str(Path(__file__).parent.parent))
from config.org import DEPTS, SECTIONS, COMPANY_ID

# ─── Known abbreviations and domain terms ─────────────────────────────────────
# Maps canonical name → extra keywords to add (domain knowledge, abbreviations)

_EXTRA: dict[str, list[str]] = {
    # 電機 depts
    "営業部":             ["営業", "売上", "受注", "売上高", "粗利", "限界粗利益", "受注額", "受注件数", "販売"],
    "設計部":             ["設計", "図面", "CAD"],
    "生産管理部":         ["生産管理", "工程", "納期", "生産"],
    "総務部":             ["総務", "人事", "KIP", "AI", "IOT", "DX"],
    "製造部":             ["製造", "加工", "塗装", "フレーム", "薄物", "生産"],
    "配線部":             ["配線", "組立", "ミス", "不良"],
    "検査部":             ["検査", "不良率"],
    "品質環境管理部":     ["品質", "環境", "不良", "クレーム", "QC", "品質管理"],
    "品質環境管理課":     ["品質", "環境", "不良", "クレーム", "QC", "品質管理"],
    "エンジニアリング部": ["EG", "EG部", "エンジニアリング", "技術"],
    # 電照 depts
    "管理部":             ["管理", "資材", "調達"],
    "808MERA":            ["808", "MERA"],
    # sections
    "東京支店":           ["東京", "Tokyo"],
    "大阪支店":           ["大阪", "Osaka"],
    "福岡支店":           ["福岡", "Fukuoka"],
    "KIP AI/IOTグループ": ["KIP", "AIIOT", "AI/IOT", "AI", "IOT", "DX"],
    "薄物1課":            ["薄物"],
    "薄物2課":            ["薄物"],
    "営業全体":           ["営業", "売上", "受注"],
    "営業-東京":          ["東京営業", "営業東京"],
    "営業-大阪":          ["大阪営業", "営業大阪"],
    "営業-福岡":          ["福岡営業", "営業福岡"],
    "営業-宮崎・沖縄":    ["宮崎", "沖縄", "宮崎沖縄"],
    "品質環境管理課":     ["品質", "不良", "クレーム"],
    "配線組立課":         ["配線", "組立"],
}

# Suffixes to strip when generating base keywords
_SUFFIXES = ["部", "課", "グループ", "支店"]


def _strip_suffix(name: str) -> str | None:
    for s in _SUFFIXES:
        if name.endswith(s) and len(name) > len(s):
            return name[: -len(s)]
    return None


def build_keywords() -> dict[str, dict]:
    """
    Returns: {keyword: {"dept": str|None, "section": str|None, "company": str|None}}
    company=None means the keyword applies to both companies.
    """
    result: dict[str, dict] = {}

    def _add(keyword: str, dept: str | None, section: str | None, company: str | None):
        kw = keyword.strip()
        if not kw:
            return
        # If already exists, widen any conflicting field to None
        if kw in result:
            existing = result[kw]
            if existing["company"] != company:
                existing["company"] = None
            if existing["dept"] != dept:
                existing["dept"] = None
            if existing["section"] != section:
                existing["section"] = None
        else:
            result[kw] = {"dept": dept, "section": section, "company": company}

    for company, depts in DEPTS.items():
        for dept in depts:
            # Canonical name itself
            _add(dept, dept, None, company)
            # Suffix-stripped base
            base = _strip_suffix(dept)
            if base:
                _add(base, dept, None, company)
            # Extra domain keywords
            for kw in _EXTRA.get(dept, []):
                _add(kw, dept, None, company)

    for company, sections in SECTIONS.items():
        # Resolve section → parent dept via ORG_CHART
        from config.org import ORG_CHART
        company_id = COMPANY_ID[company]
        org = ORG_CHART[company_id]

        for section in sections:
            # Find dept for this section
            dept = None
            for entry in org.values():
                if entry.get("section") == section:
                    dept = entry["dept"]
                    break

            _add(section, dept, section, company)
            base = _strip_suffix(section)
            if base:
                _add(base, dept, section, company)
            for kw in _EXTRA.get(section, []):
                _add(kw, dept, section, company)

    return result


def write_keywords(kw_map: dict[str, dict], out_path: Path) -> None:
    lines = [
        '"""',
        'keywords.py — Generated by keyword_build.py. Do not edit manually.',
        'Run: python config/keyword_build.py',
        '"""',
        "",
        "# keyword → {dept, section, company}  (None = not restricted)",
        "KEYWORDS: dict[str, dict] = {",
    ]
    for kw, meta in sorted(kw_map.items()):
        dept    = f'"{meta["dept"]}"'    if meta["dept"]    else "None"
        section = f'"{meta["section"]}"' if meta["section"] else "None"
        company = f'"{meta["company"]}"' if meta["company"] else "None"
        lines.append(f'    {repr(kw)}: {{"dept": {dept}, "section": {section}, "company": {company}}},')
    lines.append("}")
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(kw_map)} keywords → {out_path}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--llm", action="store_true", help="(future) LLM expansion pass")
    args = parser.parse_args()

    out = Path(__file__).parent / "keywords.py"
    kw_map = build_keywords()
    write_keywords(kw_map, out)

    if args.llm:
        print("LLM expansion not yet implemented.")


if __name__ == "__main__":
    main()
